mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('witchers.urls')),
]

witchers/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),

    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registration/', views.user_registration, name='registration'),
    path('account_edit/', views.account_edit, name='account_edit'),
    path('account_delete/', views.account_delete, name='account_delete'),
    path('account_delete_done/', views.account_delete_done, name='account_delete_done'),

    path('main_page/', views.main_page, name='main_page'),

    path('user/<username>/', views.user_details, name='user_details'),
    path('witchers_stats/', views.witchers_stats, name='witchers_stats'),

    path('add_ad/', views.add_ad, name='add_ad'),
    path('ad/<slug:post>/', views.post_details, name='post_details'),
    path('ad/<slug:post>/change_status', views.change_post_status, name='change_status'),
    path('ad/<slug:post>/delete', views.delete_post, name='delete_post'),
    path('ad/<slug:post>/edit', views.edit_post, name='edit_post'),

    path('ad/<slug:post>/apply', views.apply_to_post, name='apply'),
    path('ad/<slug:post>/cancel_application', views.cancel_post_application, name='cancel_application'),
    path('ad/<slug:post>/mark_completed', views.mark_post_as_completed, name='mark_completed'),
    path('ad/<slug:post>/rate', views.rate_witcher_work, name='rate'),

    path('my_ads/', views.my_ads, name='my_ads'),
    path('commented_ads/', views.commented_ads, name='commented_ads'),
    path('unread_comments/', views.unread_coments, name='unread_comments'),

    path('error/', views.error, name='error'),


    # Password reset
    path('password_reset/',
          auth_views.PasswordResetView.as_view(),
          name='password_reset'),
    path('password_reset/done/',
          auth_views.PasswordResetDoneView.as_view(),
          name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(),
          name='password_reset_confirm'),
    path('reset/done/',
          auth_views.PasswordResetCompleteView.as_view(),
          name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

witchers/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse

from mysite.settings import MEDIA_URL


class UserExtension(models.Model):
    USER_TYPE = [ ('customer', 'Klient'), ('witcher', 'Wiedźmin') ]

    user            = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name='extension')
    fullname        = models.CharField(max_length=150, blank=True)
    avatar          = models.ImageField(upload_to='user_avatars/', blank=True, null=True)
    type            = models.CharField(max_length=10, choices=USER_TYPE, default='customer')

    def __str__(self):
        return str(self.user)

    def get_name(self):
        if self.fullname:
            return self.fullname
        else:
            return self.user.username

    def get_avatar(self):
        if self.avatar:
            return f'{MEDIA_URL}{self.avatar}'
        else:
            return f'{MEDIA_URL}user_avatars/no_image.png'

    def get_notification_count(self):
        '''Get number of this user's post where are unread comments'''
        user_ads = Ad.objects.filter(user=self.user)
        res = 0
        for ad in user_ads:
            res += 1 if ad.get_unread_comments_count() else 0

        all_posts_with_application = Ad.objects.filter(user=self.user)\
                .filter(category__name='Zlecenie')\
                .exclude(application__isnull=True)

        posts_with_application = all_posts_with_application\
                .filter(application__is_completed=False)

        unrated_posts = all_posts_with_application\
                .filter(application__is_completed=True)\
                .filter(application__rate=0)

        res += len(posts_with_application)
        res += len(unrated_posts)

        return res

    def get_url(self):
        return reverse('user_details', args=[self.user.username])


class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Ad(models.Model):
    STATUSES = [ (0, 'Aktualne'), (1, 'Nie aktualne') ]

    slug        = models.SlugField(max_length=50, unique=True)
    status      = models.BooleanField(choices=STATUSES, default=0)
    title       = models.CharField(max_length=64)
    description = models.TextField()
    category    = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='+')
    price       = models.FloatField()
    image       = models.ImageField(upload_to='post_images/', blank=True, null=True)
    user        = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    created     = models.DateTimeField(auto_now=True)

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Ad.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{slug[:45]}-{num}'
            num += 1
        return unique_slug

    def get_created_time(self):
        now = timezone.now()
        if now.date() == self.created.date():
            return f'dzisiaj o {self.created.strftime("%H:%M")}'
        else:
            return f'{self.created.date()} o {self.created.strftime("%H:%M")}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post_details', args=[self.slug])

    def get_url(self):
        return reverse('post_details', args=[self.slug])

    def get_delete_url(self):
        return reverse('post_details', args=[self.slug]) + 'delete'

    def get_edit_url(self):
        return reverse('post_details', args=[self.slug]) + 'edit'

    def get_change_status_url(self):
        return self.get_absolute_url() + 'change_status'

    def __str__(self):
        return self.title

    def get_image(self):
        if self.image:
            return f'{MEDIA_URL}{self.image}'
        else:
            return f'{MEDIA_URL}post_images/no_image.png'

    def mark_comments_as_read(self):
        unread_comments = self.comments.filter(is_read=False)
        for comment in unread_comments:
            comment.is_read = True
            comment.save()

    def get_unread_comments_count(self):
        return self.comments.filter(is_read=False).count()


class Application(models.Model):
    user         = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')
    ad           = models.OneToOneField(Ad, on_delete=models.CASCADE, unique=True, related_name='application', null=True, blank=True)
    rate         = models.IntegerField(default=0)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user}\'s application under {self.ad}'


class Comment(models.Model):
    user    = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    ad      = models.ForeignKey(Ad, on_delete=models.CASCADE, related_name='comments')
    text    = models.TextField(blank=False)
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def get_created_time(self):
        now = timezone.now()
        if now.date() == self.created.date():
            return f'dzisiaj o {self.created.strftime("%H:%M")}'
        else:
            return f'{self.created.date()} o {self.created.strftime("%H:%M")}'

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.user, self.ad)

witchers/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
import django.core.files.images as django_images

from .models import UserExtension

from .models import Ad, Category, Comment


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control",
        "id": "nameControlInput",
        "placeholder": "Jak się nazywasz?",
        "maxlength": "20",}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "id": "passwordControlInput",
        "placeholder": "Sekretne hasło..."
        }))


class RegistrationForm(forms.ModelForm):
    error_css_class = 'error-text'
    user_type = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={"class": "form-check-input"}),
        choices=(('customer', "Klient"), ('witcher', "Wiedźmin")),
        initial='customer'
        )
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control",
        "id": "nameControlInput",
        "placeholder": "Jak się nazywasz?",
        "data-incorrect": "false",
        "maxlength": "20",}),
        error_messages={ 'unique': "Użytkownik z takim loginem już istnieje." }
        )
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control",
        "id": "emailControlInput",
        "placeholder": "Wpisz adres e-mail...",
        "data-incorrect": "false",
        "maxlength": "150",}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "id": "passwordControlInput",
        "placeholder": "Sekretne hasło...",
        "data-incorrect": "false",
        "maxlength": "150",}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "id": "repeatPasswordControlInput",
        "placeholder": "Powtórz hasło...",
        "data-incorrect": "false",
        "maxlength": "150",}))

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]


class AddAdForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'advTitle',
        'required': True,
        'placeholder': 'Wpisz tu nazwę zlecenia',
        }))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control col-12',
        'id': 'advDescription',
        'required': True,
        'rows': '3',
        'placeholder': 'Opisz tu szczegóły zlecenia',
        }))

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label='Wybierz kategorie',
        widget=forms.Select(attrs={
            'class': 'form-control col-12',
            'id': 'advType',
            'required': True,
            }))

    price = forms.FloatField(
        min_value=0,
        max_value=20000,
        error_messages={'min_value': 'Wartość ma być większa od zera!',
                        'max_value': 'Wartość ma być mniejsza lub równa 20000!'},
        widget=forms.NumberInput(attrs={
            'class': 'form-control col-12',
            'id': 'advCost',
            'placeholder': 'Cena',
            'required': True,
            }))

    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = Ad
        fields = ('title', 'description', 'category', 'price', 'image')


class AccountEditForm(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control",
        "id": "fullnameControlInput",
        "placeholder": "Jak się nazywasz?"
    }), required=False)
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)
    class Meta:
        model = UserExtension
        fields = ('fullname', 'avatar',)

    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar', False)
        if avatar:
            w, h = django_images.get_image_dimensions(avatar)
            if avatar.size > 2*1024*1024 and w != 200 and h != 200:
                raise forms.ValidationError('To musi być obrazek do 2MB i rozmiarem 200px na 200px')
            return avatar


class UserEditForm(forms.ModelForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control",
        "id": "emailControlInput",
        "placeholder": "Wpisz nowy adres e-mail...",
        "data-incorrect": "false",
    }))
    class Meta:
        model = User
        fields = ('email',)


class MyPasswordChangeForm(PasswordChangeForm):
    error_messages = {
        'password_incorrect': 'Stare hasło jest nieprawiedłowe.',
        'password_mismatch': 'Hasła nie zgadzają się.',
    }

    old_password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'placeholder': 'Wpisz swoje stare hasło'
    }))
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'placeholder': 'Wpisz nowe hasło'
        }),
        strip=False,
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'placeholder': 'Powtórz nowe hasło'
    }))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

witchers/templates/witchers/advForm.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}Nowe ogłoszenie{% endblock %}

{% block content %}
<div class="float-center">
    <form id="advForm" method="POST" action="."  class="col-lg-8 p-4 mx-lg-auto rounded " enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="mb-sm-3">Dodaj ogłoszenie</h1>
        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">Typ</label>
            {{ form.category }}
            {{ form.category.errors }}
        </div>

        <div class="form-group">
            {{ form.title }}
            {{ form.title.errors }}
            <span class="prompt">Może zawierać litery, cyfry, spację oraz .?!. Długość od 3 do 64</span>
        </div>

        <div class="form-group">
            {{ form.price }}
            {{ form.price.errors }}
            <span class="prompt"> Liczba od 0 do 20000, Format 0.00,12 lub 1,3</span>
        </div>
        
        <div class="form-group">
            {{ form.image }}
            {{ form.image.errors }}
            <span class="prompt">Lepiej gdy ogłoszenie jest z obrazkiem</span>
        </div>

        <div class="form-group">
            {{ form.description }}
            {{ form.description.errors }}
            <span class="prompt">Dopuszczalne: cyfry,litery,spacje oraz ,.?!-:(). Długość od 10 do 400</span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btnForHyper mb-2">Dodaj</button>
        </div>
    </form>

</div>
{% endblock %}

witchers/templates/witchers/commented_ads.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}Skomentowane ogłoszenia{% endblock %}

{% block content %}
{% include "witchers/pagination.html" with page=posts %}
<div class="float-center">
    <div id="myAdvs" class="p-sm-5 p-2">
        <h2 class="mb-sm-3">Skomentowane ogłoszenia <span class="badge badgeLight">{{ posts.paginator.count }}</span></h2>
        <ul class="list-group">

            {% for post in posts %}
            <li class="list-group-item row d-md-flex justify-content-between align-items-center">
                <div>
                <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                <p>Stworzono: {{ post.get_created_time }}</p>
                </div>
                <div>
                    Status:
                    <span class="badge badgeLight">{{ post.get_status_display }}</span>
                    Komentarze:
                    <span class="badge badgeLight">{{ post.comments.all.count }}</span>
                </div>
            </li>
            {% empty %}
            <p>Nie skomentowałeś jeszcze żadnych ogłoszeń. </p>
            {% endfor %}

        </ul>
    </div>
</div>
{% include "witchers/pagination.html" with page=posts %}
{% endblock %}

witchers/templates/witchers/editAdvForm.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}Zmień ogłoszenie{% endblock %}

{% block content %}
<div class="float-center">

    <form id="advForm" method="POST" action="{{ post.get_edit_url }}" class="col-lg-8 mx-lg-auto rounded" enctype="multipart/form-data">
        <h1>Zmień ogłoszenie</h1>
        {% csrf_token %}

        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">Typ</label>
            {{ form.category }}
            {{ form.category.errors }}
        </div>

        <div class="form-group">
            {{ form.title }}
            {{ form.title.errors }}
            <span class="prompt">Może zawierać litery, cyfry oraz spację. Długość od 5 do 30</span>
        </div>

        <div class="form-group">
            {{ form.price }}
            {{ form.price.errors }}
            <span class="prompt"> Liczba > 0, Format 0.00,12 lub 1,3</span>
        </div>

        <div class="form-group">
            {{ form.image }}
            {{ form.image.errors }}
            <span class="prompt">Lepiej gdy ogłoszenie jest z obrazkiem</span>
        </div>

        <div class="form-group">
            {{ form.description }}
            {{ form.description.errors }}
            <span class="prompt">Dopuszczalne: cyfry,litery,pacje,{,.?!}. Długość od 10 do 100</span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn mb-2">Zachowaj zmiany</button>
        </div>
    </form>

</div>
{% endblock %}

witchers/templates/witchers/error.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}Moje ogłoszenia{% endblock %}

{% block content %}
<h1>Nie możesz usunąć zlecenia które jest aktualnie wykonywane lub jest już wykonane.</h1>
<a href="{{ prev }}"><button class="btn">Cofnij</button></a>
{% endblock %}

witchers/templates/witchers/myAdv.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}Moje ogłoszenia{% endblock %}

{% block content %}
{% include "witchers/pagination.html" with page=posts %}
<div class="float-center mx-auto my-1">
    <div id="myAdvs" class="p-sm-5 p-2">
        <h2 class="mb-sm-3">Moje ogłoszenia <span class="badge badgeLight">{{ posts.paginator.count }}</span></h2>
        <ul class="list-group">
            {% for post in posts %}
            <li class="list-group-item row d-lg-flex justify-content-between align-items-center">
                <a href="{{ post.get_absolute_url }}">
                    <p class="card-title my-auto">{{ post.title }}</p>
                </a>
                Stworzono: {{ post.get_created_time }}
                <div class="d-md-flex d-inline  align-items-center">
                    <div>
                        Status:
                        <span class="badge badgeLight">{{ post.get_status_display }}</span>
                        Komentarze:
                        <span class="badge badgeLight">{{ post.comments.all.count }}</span>
                    </div>
                    <div>
                        <a href="{{ post.get_edit_url }}" class="btn btnForHyper">Edytuj</a>
                        <a href="{{ post.get_delete_url }}" class="btn btnForHyper">Usuń</a>
                    </div>
                </div>
            </li>
            {% empty %}
            <p>Nie dodałeś jeszcze żadnych ogłoszeń. <a href="{% url "add_ad" %}"><span class="badge badgeLight">Dodaj
                        pierwsze.</span></a></p>
            {% endfor %}

        </ul>
    </div>
</div>
{% include "witchers/pagination.html" with page=posts %}
{% endblock %}

witchers/templates/witchers/pagination.html
{% if page.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links mx-auto">
        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}"> ← </a>
        {% else %}
        ←
        {% endif %}

        <span class="current">
            {% for i in page.paginator.page_range %}
                {% if i == page.number %}
                <span class="badge badgeLight">  {{ i }}</span>
                {% else %}
                    <a href="?page={{ i }}"><span class="badge"> {{ i }}</span></a>
                {% endif %}
            {% endfor %}
        </span>

        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}"> → </a>
        {% else %}
        →
        {% endif %}
    </span>
</div>
{% endif %}

witchers/templates/witchers/unread_comments.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}Moje ogłoszenia{% endblock %}

{% block content %}
<div class="float-center">
    <div id="myAdvs" class="p-sm-5 p-2">
        <h2 class="mb-sm-3">Ogłoszenia z nowymi komentarzami<span class="badge badge-secondary">{{ posts.count }}</span></h2>
        <ul class="list-group">

            {% for post in posts %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                Stworzono: {{ post.get_created_time }}
                <div>
                    Status:
                    <span class="badge badge-secondary">{{ post.get_status_display }}</span>
                    Komentarze:
                    <span class="badge badge-secondary">{{ post.comments.all.count }}</span>
                </div>
            </li>
            {% empty %}
            <p>Nie ma nowych komentarzy.</p>
            {% endfor %}
        </ul>

        <h2 class="mb-sm-3">Zlecenia które są w trakcie wykonania<span class="badge badge-secondary">{{ posts_with_application.count }}</span></h2>
        <ul class="list-group">
            {% for post in posts_with_application %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                Stworzono: {{ post.get_created_time }}
                <div>
                    Status:
                    <span class="badge badge-secondary">{{ post.get_status_display }}</span>
                    Komentarze:
                    <span class="badge badge-secondary">{{ post.comments.all.count }}</span>
                </div>
            </li>
            {% empty %}
            <p>Twoje zlecenia nie są aktualnie wykonywane.</p>
            {% endfor %}
        </ul>

        <h2 class="mb-sm-3">Zlecenia które czekają na twoją ocene<span class="badge badge-secondary">{{ unrated_posts.count }}</span></h2>
        <ul class="list-group">
            {% for post in unrated_posts %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                Stworzono: {{ post.get_created_time }}
                <div>
                    Status:
                    <span class="badge badge-secondary">{{ post.get_status_display }}</span>
                    Komentarze:
                    <span class="badge badge-secondary">{{ post.comments.all.count }}</span>
                </div>
            </li>
            {% empty %}
            <p>Twoje zlecenia nie są aktualnie wykonywane.</p>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

witchers/templates/witchers/user_adv.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}{{ user.extension.get_name }}{% endblock %}

{% block content %}
{% include "witchers/pagination.html" with page=posts %}
<div class="float-center mx-auto my-1">
    <div id="myAdvs" class="p-sm-5 p-2">
        {% if user.extension.type == "witcher" %}
        <div class="jumbotron text-center bg-dark">
            <h2><img src="{{ user.extension.get_avatar }}" class="user-avatar">{{user.extension.get_name}}</h2>
        </div>

        <div class="jumbotron bg-dark">
            {% if stats %}
            <h1 class="white-header">Statystyka konta</h1>
            <ol class="container">
                <li class="font-weight-bold">Średnia ocena za zlecenie: <span class="badge badge-secondary">{{ stats.rate }}</span></li>
                <li class="font-weight-bold">Ilość wykonanych zleceń: <span class="badge badge-secondary">{{ stats.completed }} / {{ stats.all }}</span></li>
                <li class="font-weight-bold">Ilość rezygnacji ze zleceń: <span class="badge badge-secondary">{{ stats.canceled }}</span></li>
            </ol>
            {% else %}
            <h3>Ten wiedźmin jeszcze nie wykonał żednego zlecenia.</h3>
            {% endif %}
            {% endif %}

            <h2 class="mb-sm-3 white-header">Ogłoszenia użytkownika {{ user.extension.get_name }} <span class="badge badge-secondary">{{ posts.paginator.count }}</span></h2>
            <ul class="list-group">
                {% for post in posts %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                    Stworzono: {{ post.get_created_time }}
                    <div>
                        Status:
                        <span class="badge badge-secondary">{{ post.get_status_display }}</span>
                        Komentarze:
                        <span class="badge badge-secondary">{{ post.comments.all.count }}</span>
                    </div>
                </li>
                {% empty %}
                <p>Ten użytkownik jeszcze nie dodał żadnych ogłoszeń.</p>
                {% endfor %}

            </ul>
        </div>
    </div>
</div>
{% include "witchers/pagination.html" with page=posts %}
{% endblock %}

witchers/templates/witchers/witchers_stats.html
{% extends "witchers/base.html" %}
{% load static %}

{% block title %}Moje zlecenia{% endblock %}

{% block content %}
<div class="float-center mx-auto my-1">
        <div id="myAdvs" class="p-sm-5 p-2">
            <div class="jumbotron text-center bg-dark">
                <h2><img src="{{ request.user.extension.get_avatar }}" class="user-avatar">{{request.user.extension.get_name}}</h2>
            </div>

            <div class="jumbotron bg-dark">

                {% if stats %}
                <h1 class="white-header">Statystyka konta</h1>
                <ol class="container">
                    <li class="font-weight-bold">Średnia ocena za zlecenie: <span class="badge badge-secondary">{{ stats.rate }}</span></li>
                    <li class="font-weight-bold">Ilość wykonanych zleceń: <span class="badge badge-secondary">{{ stats.completed }} / {{ stats.all }}</span></li>
                    <li class="font-weight-bold">Ilość rezygnacji ze zleceń: <span class="badge badge-secondary">{{ stats.canceled }}</span></li>
                </ol>
                {% else %}
                <h3>Jeszcze nie wykonałeś żednego zlecenia.</h3>
                {% endif %}

                <h1 class="mb-sm-3 white-header">Wykonywane zlecenia<span class="badge badge-secondary">{{ posts.paginator.count }}</span></h1>
                <ul class="list-group">
                    {% for appl in uncompleted %}
                    {% with appl.ad as post %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                        Stworzono: {{ post.get_created_time }}
                        <div>
                            Status:
                            <span class="badge badge-secondary">{{ post.get_status_display }}</span>
                            Komentarze:
                            <span class="badge badge-secondary">{{ post.comments.all.count }}</span>
                        </div>
                    </li>
                    {% endwith %}
                    {% empty %}
                    <p>Nie wykonujesz w tej chwili zleceń.</p>
                    {% endfor %}
                </ul>

                <h1 class="mb-sm-3 white-header">Wykonane ale nie ocenione zlecenia<span class="badge badge-secondary">{{ posts.paginator.count }}</span></h1>
                <ul class="list-group">
                    {% for appl in unrated %}
                    {% with appl.ad as post %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                        Stworzono: {{ post.get_created_time }}
                        <div>
                            Status:
                            <span class="badge badge-secondary">{{ post.get_status_display }}</span>
                            Komentarze:
                            <span class="badge badge-secondary">{{ post.comments.all.count }}</span>
                        </div>
                    </li>
                    {% endwith %}
                    {% empty %}
                    <p>Nie ma takich zleceń.</p>
                    {% endfor %}
                </ul>

                <h1 class="mb-sm-3 white-header">Wykonane zlecenia<span class="badge badge-secondary">{{ posts.paginator.count }}</span></h1>
                <ul class="list-group">
                    {% for appl in completed %}
                    {% with appl.ad as post %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{{ post.get_absolute_url }}"><p class="card-title my-auto">{{ post.title }}</p></a>
                        Stworzono: {{ post.get_created_time }}
                        <div>
                            Status:
                            <span class="badge badge-secondary">{{ post.get_status_display }}</span>
                            Komentarze:
                            <span class="badge badge-secondary">{{ post.comments.all.count }}</span>
                        </div>
                    </li>
                    {% endwith %}
                    {% empty %}
                    <p>Jeszcze nie wykonałeś żadnego zlecenia.</p>
                    {% endfor %}
                </ul>

            </div>
        </div>

</div>
{% endblock %}